import Link from "next/link";
import { fetchCommunityHooks } from "@/lib/supabase";
import CommunityBoard from "@/components/CommunityBoard";

export const metadata = {
  title: "Community — Top Hooks | Hook AI",
  description:
    "The highest-scoring marketing hooks and angles generated by Hook AI users. Filter by channel and copy the winners to your own campaigns.",
};

export const dynamic = "force-dynamic";

export default async function CommunityPage() {
  const hooks = await fetchCommunityHooks();

  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-4xl px-4 py-10">
        <div className="text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50/80 px-3 py-1 text-xs font-medium text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/60 dark:text-indigo-300">
            The Swipe File
          </span>
          <h1 className="mt-3 text-3xl font-bold tracking-tight">Top Hooks of the Week</h1>
          <p className="mx-auto mt-2 max-w-lg text-sm text-zinc-500">
            The highest-scoring hooks generated by Hook AI users. Filter by channel, copy the winners, and
            steal the angles that are working.
          </p>
        </div>

        <CommunityBoard hooks={hooks} />

        <div className="card-elevated mt-8 rounded-2xl border border-zinc-200 bg-white p-6 text-center dark:border-zinc-800 dark:bg-zinc-900">
          <p className="text-sm text-zinc-500">Want to get your hook on the board?</p>
          <Link
            href="/#tool"
            className="bg-gradient-brand mt-3 inline-block rounded-xl px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
          >
            Generate your first hooks
          </Link>
        </div>

        <p className="mt-6 text-center text-xs text-zinc-400">
          Results are anonymized and scored by Hook AI&apos;s CTR prediction engine.
        </p>
      </div>
    </main>
  );
}