import Link from "next/link";
import { fetchCommunityHooks } from "@/lib/supabase";
import { CHANNEL_LABELS } from "@/lib/types";

export const metadata = {
  title: "Community — Top Hooks | Hook AI",
  description: "The highest-scoring marketing hooks and angles generated by Hook AI users this week.",
};

export const dynamic = "force-dynamic";

export default async function CommunityPage() {
  const hooks = await fetchCommunityHooks();

  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-4xl px-4 py-10">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight">The Hook Board</h1>
          <p className="mt-2 text-sm text-zinc-500">
            The highest-scoring hooks and angles generated by Hook AI users. Watch what&apos;s winning.
          </p>
        </div>

        {hooks.length === 0 ? (
          <div className="card-elevated mt-10 rounded-2xl border border-zinc-200 bg-white p-12 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-xl font-semibold">No hooks yet.</p>
            <p className="mt-1 text-sm text-zinc-500">
              Be the first — run an analysis and your best hooks will appear here.
            </p>
            <Link
              href="/#tool"
              className="bg-gradient-brand mt-5 inline-block rounded-xl px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
            >
              Generate your first hooks
            </Link>
          </div>
        ) : (
          <div className="mt-8 space-y-3">
            {hooks.map((h, i) => (
              <div key={i} className="card-elevated flex items-center gap-4 rounded-2xl border border-zinc-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-indigo-200 dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-indigo-800">
                <span className="text-gradient w-8 shrink-0 text-center text-xl font-bold">{i + 1}</span>
                <div className="min-w-0 flex-1">
                  <p className="font-semibold leading-snug">{h.hook}</p>
                  <p className="mt-1 flex flex-wrap items-center gap-2 text-xs text-zinc-500">
                    {h.channel && CHANNEL_LABELS[h.channel as keyof typeof CHANNEL_LABELS] && (
                      <span className="rounded-full bg-indigo-50 px-2 py-0.5 font-medium text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">
                        {CHANNEL_LABELS[h.channel as keyof typeof CHANNEL_LABELS]}
                      </span>
                    )}
                    {h.psychology && (
                      <span className="rounded-full bg-zinc-100 px-2 py-0.5 dark:bg-zinc-800">{h.psychology}</span>
                    )}
                    {h.topic && <span className="text-zinc-400">for {h.topic}</span>}
                  </p>
                </div>
                <div className="shrink-0 text-right">
                  <span className="bg-gradient-brand rounded-full px-3 py-1 text-sm font-bold text-white">
                    {h.score}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}

        <p className="mt-8 text-center text-xs text-zinc-400">
          Results are anonymized and scored by Hook AI&apos;s CTR prediction engine.
        </p>
      </div>
    </main>
  );
}