"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { AnalyzeResult } from "@/lib/types";
import { decodeShareData } from "@/lib/analytics";
import { detectReferral } from "@/lib/referral";
import ResultView from "@/components/ResultView";
import Link from "next/link";

export default function SharedResultsPage() {
  return (
    <Suspense fallback={<p className="mx-auto mt-10 max-w-6xl px-4 text-sm text-zinc-500">Loading…</p>}>
      <SharedResults />
    </Suspense>
  );
}

function SharedResults() {
  const params = useSearchParams();
  const d = params.get("d");
  const [result, setResult] = useState<AnalyzeResult | null>(null);
  const [failed, setFailed] = useState(false);
  const [ref] = useState<{ code: string; first: boolean } | null>(() => {
    const r = detectReferral();
    return r.refCode ? { code: r.refCode, first: r.firstTime } : null;
  });

  useEffect(() => {
    if (!d) return;
    let active = true;
    decodeShareData(d)
      .then((r) => {
        if (!active) return;
        if (r) setResult(r);
        else setFailed(true);
      })
      .catch(() => {
        if (active) setFailed(true);
      });
    return () => {
      active = false;
    };
  }, [d]);

  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-6xl px-4 py-10">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">
              {result ? <>Hooks for “{result.topic}”</> : "Shared results"}
            </h1>
            {result && (
              <p className="mt-1 text-sm text-zinc-500">
                {result.aiPowered ? `Generated by Hook AI · ${result.model}` : "Generated by Hook AI"} · {result.hooks.length} hooks
              </p>
            )}
          </div>
          <Link
            href="/#tool"
            className="bg-gradient-brand rounded-xl px-4 py-2 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
          >
            Make your own
          </Link>
        </div>

        {ref && (
          <div className="card-elevated mb-6 rounded-2xl border border-indigo-200 bg-gradient-soft p-4 dark:border-indigo-950 dark:bg-indigo-950/40">
            <p className="text-sm text-indigo-700 dark:text-indigo-300">
              {ref.first
                ? `You were referred to Hook AI${ref.code !== "anon" ? ` by someone (${ref.code})` : ""}. Share your own results to earn free runs.`
                : `Shared by a Hook AI user${ref.code !== "anon" ? ` (${ref.code})` : ""}.`}
            </p>
          </div>
        )}

        {!d && (
          <div className="card-elevated rounded-2xl border border-zinc-200 bg-white p-12 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-xl font-semibold">This link doesn&apos;t contain valid results.</p>
            <p className="mt-1 text-sm text-zinc-500">It may be expired or malformed.</p>
            <Link
              href="/"
              className="bg-gradient-brand mt-5 inline-block rounded-xl px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
            >
              Go generate your own hooks
            </Link>
          </div>
        )}

        {d && !result && !failed && (
          <div className="flex items-center gap-2 text-sm text-zinc-500">
            <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-zinc-300 border-t-indigo-500" />
            Loading shared results…
          </div>
        )}

        {failed && (
          <div className="card-elevated rounded-2xl border border-zinc-200 bg-white p-12 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-xl font-semibold">This link doesn&apos;t contain valid results.</p>
            <p className="mt-1 text-sm text-zinc-500">It may be expired or malformed.</p>
            <Link
              href="/"
              className="bg-gradient-brand mt-5 inline-block rounded-xl px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
            >
              Go generate your own hooks
            </Link>
          </div>
        )}

        {result && <ResultView result={result} />}
      </div>
    </main>
  );
}
