"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { AnalyzeResult } from "@/lib/types";
import { decodeShareData } from "@/lib/analytics";
import ResultView from "@/components/ResultView";
import Link from "next/link";

export default function SharedResultsPage() {
  return (
    <Suspense fallback={<p className="mx-auto mt-10 max-w-6xl px-4 text-sm text-zinc-500">Loading…</p>}>
      <SharedResults />
    </Suspense>
  );
}

function SharedResults() {
  const params = useSearchParams();
  const d = params.get("d");
  const [result, setResult] = useState<AnalyzeResult | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (!d) return;
    let active = true;
    decodeShareData(d)
      .then((r) => {
        if (!active) return;
        if (r) setResult(r);
        else setFailed(true);
      })
      .catch(() => {
        if (active) setFailed(true);
      });
    return () => {
      active = false;
    };
  }, [d]);

  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-6xl px-4 py-10">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">
              {result ? <>Hooks for “{result.topic}”</> : "Shared results"}
            </h1>
            {result && (
              <p className="mt-1 text-sm text-zinc-500">
                {result.aiPowered ? `Generated by Hook AI · ${result.model}` : "Generated by Hook AI"} · {result.hooks.length} hooks
              </p>
            )}
          </div>
          <Link
            href="/#tool"
            className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-500"
          >
            Make your own
          </Link>
        </div>

        {!d && (
          <div className="rounded-2xl border border-zinc-200 bg-white p-8 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-lg font-semibold">This link doesn&apos;t contain valid results.</p>
            <p className="mt-1 text-sm text-zinc-500">It may be expired or malformed.</p>
            <Link
              href="/"
              className="mt-4 inline-block rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-500"
            >
              Go generate your own hooks
            </Link>
          </div>
        )}

        {d && !result && !failed && <p className="text-sm text-zinc-500">Loading shared results…</p>}

        {failed && (
          <div className="rounded-2xl border border-zinc-200 bg-white p-8 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-lg font-semibold">This link doesn&apos;t contain valid results.</p>
            <p className="mt-1 text-sm text-zinc-500">It may be expired or malformed.</p>
            <Link
              href="/"
              className="mt-4 inline-block rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-500"
            >
              Go generate your own hooks
            </Link>
          </div>
        )}

        {result && <ResultView result={result} />}
      </div>
    </main>
  );
}
