import type { Metadata } from "next";
import Link from "next/link";
import { getShare } from "@/lib/shares";
import ResultView from "@/components/ResultView";
import CampaignPlanView from "@/components/CampaignPlanView";

export const metadata: Metadata = {
  title: "Shared campaign · Hook AI",
  description: "A marketing campaign generated with Hook AI — hooks, angles, plan, and health score.",
};

export default async function SharePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const result = await getShare(slug);

  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-6xl px-4 py-10">
        {!result ? (
          <div className="card-elevated mx-auto max-w-lg rounded-2xl border border-zinc-200 bg-white p-12 text-center dark:border-zinc-800 dark:bg-zinc-900">
            <p className="text-xl font-semibold">This link isn&apos;t valid.</p>
            <p className="mt-1 text-sm text-zinc-500">It may have been unpublished or the slug is wrong.</p>
            <Link
              href="/campaign"
              className="bg-gradient-brand mt-5 inline-block rounded-xl px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
            >
              Build your own campaign
            </Link>
          </div>
        ) : (
          <>
            <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <h1 className="text-3xl font-bold tracking-tight">{result.topic}</h1>
                <p className="mt-1 text-sm text-zinc-500">
                  {result.aiPowered ? `Generated by Hook AI · ${result.model}` : "Generated by Hook AI"} ·{" "}
                  {result.hooks.length} hooks{result.plan ? ` · health ${result.plan.healthScore}/100 (${result.plan.healthGrade})` : ""}
                </p>
              </div>
              <Link
                href="/campaign"
                className="bg-gradient-brand rounded-xl px-4 py-2 text-sm font-semibold text-white shadow-md shadow-indigo-500/25 transition hover:brightness-110"
              >
                Build your own
              </Link>
            </div>

            {result.plan && (
              <div className="mb-8">
                <CampaignPlanView result={result} />
              </div>
            )}

            <ResultView result={result} />
          </>
        )}
      </div>
    </main>
  );
}
