import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Hook AI",
  description: "Terms of Service for using Hook AI, the AI-powered marketing hook generator.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <main className="flex-1">
      <div className="mx-auto w-full max-w-3xl px-4 py-14">
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: August 2026</p>

        <div className="prose mt-8 space-y-6 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">1. Agreement</h2>
            <p>
              By accessing or using Hook AI (the &quot;Service&quot;), you agree to these Terms of Service. If you do not agree,
              please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">2. The Service</h2>
            <p>
              Hook AI provides AI-generated marketing hooks, headlines, and campaign-planning suggestions. Output is
              generated by artificial intelligence and provided for inspiration and testing. It is your responsibility to
              review, verify, and edit all output before use, including compliance with platform and legal requirements.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">3. Accounts &amp; Credits</h2>
            <p>
              A free account gives you an initial credit balance and limited daily free runs. Credits may be purchased and
              are non-refundable except as required by law. Free daily runs and bonuses may be changed or removed at any
              time. You are responsible for keeping your account credentials secure.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-inside list-disc space-y-1">
              <li>violate any law or regulation;</li>
              <li>infringe the rights of others;</li>
              <li>interfere with or disrupt the Service, including automated abuse of our forms or APIs;</li>
              <li>attempt to access another user&apos;s account or data.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">5. No Warranty</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee
              that results, predictions, or scores will be accurate or achieve any particular outcome.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Hook AI shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages, or any loss of profits or data, arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">7. Termination</h2>
            <p>
              We may suspend or terminate access to the Service at our discretion, including for violations of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">8. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">9. Contact</h2>
            <p>
              Questions about these Terms: <Link href="mailto:gitvamshidhar@gmail.com" className="text-indigo-600 hover:underline dark:text-indigo-400">gitvamshidhar@gmail.com</Link>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}